sudo: false
language: java
jdk:
- oraclejdk7
- oraclejdk8
addons:
  apt:
    packages:
    - rpm
before_deploy:
- mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
- mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
- rm -f target/original-*.jar
- export RELEASE_PKG_FILE=$(ls target/*.jar)
- echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  file:
  - "${RELEASE_PKG_FILE}"
  - "${RELEASE_DEB_FILE}"
  - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk7
env:
  global:
    secure: 1dOixnZEm3EGX889VfrY6UuH/Sn70v+MUePLNafCVvCvfUt4qwGHA6GM7cyZMzrBNbwJq8+P3mZSffGpbbXMuI9YbG9CmJRL77b8EZoGbW/mZ9oCMUxeXLu5F1I2JSt3rJnzLuZ2vVtpB615aSp2iBjCXlsdSYli6N15V35t/x/sLQ0zTUvTbzVaxD39wI+zMH1n+C72hVVRvWwa959MM8lHP3na3Mj80lBA6la0Is1/yGHq14hWL5TbNkHQx7uFU7PD1Vy5GKazyyI+VwdOpdZsEx3jwNHMwqUAwfzVlZciz3vQ0KWxIUxf3QpvoS1P6mDdPfUTo5DPlM2wgQKvcWUGURQftSX+xIEMfmQWAV8JsAGzHAbA7d+60Yu3N07pv3HJilgf8fHTeByFRL2bkSvi2S9XGcRcRcH0qHbajfErsR4pCeU0/9wqqZ53IzLjaPxAG+k0hBV6sDQF6iZzgnK5ZjFGTdZzMKkAuOIFXm3hj+/rWEyoncp2cCph6QcdPIqTXzrMKVyOt4IIPzfI033EoIehOuMX2dzcx1Lgueh3hL2lL8EzXKJgtdL2im28ukE8htaWrsO4UN+UelHDX+8IGZC4tOPVylQTYS6AW9+dtpGJDbgdUcSw52cBIauPuADwxXopKAaGnNLl7YKtT01nY8gisfPuKooYV4qzcTE=
